<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="UTF-8">
    <meta name="google" content="notranslate">
    <meta http-equiv="Content-Language" content="en">
    <title></title>
    <style>
        body {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            font-size: 11px;
            font-style: normal;
            font-weight: 400;
            color: #000;
        }

        .outerDiv {
            width: 225px;
            height: 100%;
            margin: 30px 20px;
        }

        .chatArea {
            height: 300px;
            border: 1px solid gray
        }

        .container {
            display: flex;
        }

        .column {
            flex: 1;
        }

        .column-1 {
            order: 1;
            border-right: solid 1px lightgray;
        }

        .column-2 {
            order: 2;
            border-right: solid 1px lightgray;
        }

        .column-3 {
            order: 3
        }

        .userInfo {
            width: 200px;
        }

        .gridRow {
            display: grid;
            grid-template-columns: minmax(auto, 50%) 25% 25%;
            border-bottom: 1px solid lightgray;
            white-space:nowrap;
        }

        button{
            font-size:12px;
            margin: 5px 5px 0 0;
        }
    </style>
    <script type="text/javascript" src="../Scripts/jquery-1.6.4.min.js"></script>
     <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.3.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">
        var chat = $.connection.chatHub;        

        $.connection.hub.start().done
            (function () {
                    chat.server
                        .populateAgent();
            }).fail(function () { alert("signalR connection failed"); });

    </script>
    <script type="text/javascript">
        var json = [
            ["SK Dutta<br/>skd@officeclip.com", "Sep 24, 2018<br/>10:15PM", "<button type='R' sid='213'>Release</button><button>End</button>"],
            ["John Doe<br/>jdoe@jd.com", "Jan 18, 2018<br/>9:04AM", "<button>Accept</button><button>End</button>"]
        ];

        arrayToGrid = function (gridData) {
            var grid = $('<div></div>');
            $(gridData).each(function (i, rowData) {
                var row = $('<div class="gridRow"></div>');
                $(rowData).each(function (j, cellData) {
                    row.append($('<div>' + cellData + '</div>'));
                });
                grid.append(row);
            });
            return grid;
        };

        $(document).ready(function () {
            $('.topRow').append(arrayToGrid(json));

            $('button[type="R"]').click(function () {
                alert($(this).attr('sid'));
            });

            $('button[type="A"]').click(function () {
                alert($(this).attr('sid'));
            });

        });

    </script>
</head>
<body>
    <div class="container">
        <div class="column column-1">
            <div class="outerDiv">
                <div id="chatarea" class="chatArea">
                </div>
                <div style="margin-top: 5px">
                    <div>
                        <textarea id="chatText" rows="5" style="width: 100%"></textarea>
                    </div>
                    <div style="margin-top: 5px; text-align: right">
                        <button>Close</button>
                        <button id="btnSend" onclick="btnSendClick()">Send</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="column column-2">
            <div class="userInfo">
                <div style="text-align:center; font-weight: bold">
                    User Info 
                </div>
            </div>
        </div>
        <div class="column column-3">
            <div>
                <div style="text-align:center; height: 200px">
                    <div class="topRow">
                    </div>
                </div>
                <div style="text-align:center; font-weight: bold;">
                    Previous Chats
                </div>
            </div>
        </div>
    </div>
</body>
</html>
