<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="endUserChat.aspx.cs" Inherits="OfficeClip.LiveChat.Chat.endUserChat" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <style>
        body {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            font-size: 11px;
            font-style: normal;
            font-weight: 400;
            color: #000;
        }

        .outerDiv {
            width: 300px;
            height: 100%;
            margin: 30px 20px;
        }

        .chatArea {
            height: 325px;
            border: 1px solid gray
        }

        .statusLine {
            color: #777;
            margin-bottom: 4px;
            margin-top: 0;
        }

        .chatEnduserLine {
            margin-bottom: 4px;
            margin-top: 0;
        }

            .chatEnduserLine span {
                font-weight: 700;
            }

        .chatAgentLine {
            color: Green;
            margin-bottom: 4px;
            margin-top: 0;
        }

            .chatAgentLine span {
                color: Green;
                font-weight: 700;
            }
    </style>
    <script type="text/javascript" src="Scripts/jquery-1.6.4.min.js"></script>
    <script type="text/javascript" src="Scripts/js.cookie.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.3.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">
        // Declare a proxy to reference the hub.
        var chat = $.connection.chatHub;
        // Start the connection.
        $.connection.hub.start().done

            (function () {

                isCookiePresent = function () {
                    var cookiePresent = Cookies.get("name");
                    return (
                        typeof cookiePresent !== 'undefined' &&
                        cookiePresent !== null);
                };

                btnSendClick = function () {
                    chat = $.connection.chatHub;
                    $.connection.hub.start();
                };

                $(document).ready(function () {
                    if (isCookiePresent()) {
                        var name = Cookies.get("name");
                        var email = Cookies.get("email");
                        chat.server
                            .populateCustomer(name, email)
                            .done(function (connectionId) {
                                $("#hdnConnectionId").val(connectionId);
                            });
                    }
                });

            }).fail(function () { alert("signalR connection failed");});


    </script>

</head>
<body>
    <div>
        <img id="imgLogo" runat="server" />
    </div>
    <div class="outerDiv">
        <div id="chatarea" class="chatArea">
            <p class="statusLine">
                Please wait. A support representative will join shortly.
            </p>
            <p class="chatEnduserLine">
                <span>User: </span>Hello
            </p>
            <p class="chatAgentLine">
                <span>Admin: </span>Hello 2
            </p>
        </div>
        <div style="margin-top: 5px">
            <form>
                <div>
                    <textarea id="chatText" rows="5" style="width: 100%"></textarea>
                </div>
                <div style="margin-top: 5px; text-align: right">
                    <button>Close</button>
                    <button id="btnSend" onclick="btnSendClick">Send</button>
                </div>
                <input type="hidden" id="hdnConnectionId" />
            </form>
        </div>
    </div>
</body>
</html>
