<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="endUserChat.aspx.cs" Inherits="OfficeClip.LiveChat.Chat.endUserChat" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <style>
        body {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            font-size: 11px;
            font-style: normal;
            font-weight: 400;
            color: #000;
        }

        .outerDiv {
            width: 300px;
            height: 100%;
            margin: 30px 20px;
        }

        .chatArea {
            height: 325px;
            border: 1px solid gray
        }

        .statusLine {
            color: #777;
            margin-bottom: 4px;
            margin-top: 0;
        }

        .chatEnduserLine {
            margin-bottom: 4px;
            margin-top: 0;
        }

            .chatEnduserLine span {
                font-weight: 700;
            }

        .chatAgentLine {
            color: Green;
            margin-bottom: 4px;
            margin-top: 0;
        }

            .chatAgentLine span {
                color: Green;
                font-weight: 700;
            }
    </style>
    <script type="text/javascript" src="Scripts/jquery-1.6.4.min.js"></script>
    <script type="text/javascript" src="Scripts/js.cookie.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.3.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">
        // Declare a proxy to reference the hub.
        var chat = $.connection.chatHub;
        var name = '';

        chat.client.showStatusLine =
            function (statusString) {
                showClientMessage('', statusString, "statusLine");
            };

        isCookiePresent = function () {
            var cookiePresent = Cookies.get("name");
            return (
                typeof cookiePresent !== 'undefined' &&
                cookiePresent !== null);
        };

        encodedValue = function (value) {
            return $("<div />").text(value).html();
        };

        $.connection.hub.connectionSlow = function(){console.log("[" + (new Date()).toString() + "] SignalR Connection Slow");};
        $.connection.hub.reconnecting = function(){console.log("[" + (new Date()).toString() + "] SignalR Connection Reconnecting"); };
        $.connection.hub.reconnected = function(){console.log("[" + (new Date()).toString() + "] SignalR Connection Reconnected");};
        $.connection.hub.disconnected = function(){console.log("[" + (new Date()).toString() + "] SignalR Connection Disconnected"); };
        $.connection.hub.stateChanged = function () { console.log("[" + (new Date()).toString() + "] SignalR StateChange") };
        $.connection.hub.logging = true;
        

        showClientMessage = function (name, message, chatClass) {
            var encodedName =
                (name !== '')
                    ? encodedValue(name) + ': '
                    : '';
            var innerMessage =
                '<p class="'
                    + chatClass
                    + '">'
                    + encodedName
                    + encodedValue(message)
                    + '</p>';
            $(".chatArea").append(innerMessage);
        };

        chat.client.showChatEndMessage = function () {
            showClientMessage(
                "",
                "The chat has ended",
                "statusLine"
            );
        };

        chat.client.broadcastMessage = function (name, message, fromCustomer) {
            var chatClass =
                fromCustomer
                    ? "chatEnduserLine"
                    : "chatAgentLine";

            showClientMessage(
                name,
                message,
                chatClass);
        };

        chat.client.enableChat = function () {

        };

        chat.client.showAgentAvailableMessage = function (name) {
            showClientMessage(
                '',
                "Agent " + name + " has joined the chat",
                "statusLine"
            );
        };

        btnSendClick = function () {
            chat.server.send(name, $("#chatText").val(), true);
            $('#chatText').val('').focus();
        };

        btnCloseClick = function () {
            alert("connection is stopping");
            $.connection.hub.stop(false);
        };


        // Start the connection.
        $.connection.hub.start().done
            (function () {

                if (isCookiePresent()) {
                    name = Cookies.get("name");
                    var email = Cookies.get("email");
                    chat.server
                        .populateCustomer(name, email);
                }

            }).fail(function () { alert("signalR connection failed"); });

    </script>

</head>
<body>
    <div>
        <img id="imgLogo" runat="server" />
    </div>
    <div class="outerDiv">
        <div id="chatarea" class="chatArea">
        </div>
        <div style="margin-top: 5px">
            <div>
                <textarea id="chatText" rows="5" style="width: 100%"></textarea>
            </div>
            <div style="margin-top: 5px; text-align: right">
                <button id="btnClose" onclick="btnCloseClick()">Close</button>
                <button id="btnSend" onclick="btnSendClick()">Send</button>
            </div>
        </div>
    </div>
</body>
</html>
